### ISSUE TITLE
installation attempts to access remote server

### ISSUE THREAD

**Issue by dsheets** [fdopen/uwt#1]
https://github.com/fdopen/uwt/blob/master/libuv-compile.sh#L17 is uncool.

Why does it do this? Can you just make libuv a dependency/depext?

Also, version 0.0.1 published in opam uses the old broken URL and so fails every build now.

**Comment by fdopen** [comment]
Ok,
I've made it optional ( https://github.com/fdopen/uwt/commit/ec04354631d0892e302652ec788825ccf2a0be86 ) and fixed the broken URL ( https://github.com/ocaml/opam-repository/pull/4401 )
