### ISSUE TITLE
Refactor >7000 line C source file

### ISSUE THREAD

**Issue by DemiMarie** [fdopen/uwt#3]
[src/uwt_stubs.c](https://github.com/fdopen/uwt/blob/master/src/uwt_stubs.c) is a >7000 line long blob that is difficult to understand.  It should be split into smaller files.

**Comment by fdopen** [comment]
The file is already divided internally in different sections (compatible with emacs folding mode). But since it's basically just cut&paste, I can also split it up in several files ... 52574f8c716044feef700e7ce81f6f6eb38656db.
